version: '3.8'

services:
  statis:
    build: .
    container_name: statis
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./fonts:/app/fonts
      - ./icons:/app/icons
    environment:
      - PORT=8080
      - CONFIG_PATH=/config/config.yaml